import { NextResponse } from "next/server";
import {
  requireDashboardUser,
  getActiveRestrictions,
  syncEmailVerificationRestriction,
  canUserLogin,
  RestrictionQueryError,
} from "@/lib/auth";
import { db } from "@/lib/db";
import { getDashboardData, newId, normalizeUsername, toProfileDto } from "@/lib/dashboard-data";
import { isPlaceholderHandle, isAutoGeneratedHandle, normalizeHandle, validateHandle } from "@/lib/handle";

export const runtime = "nodejs";

const RESERVED_USERNAMES = new Set([
  "admin",
  "administrator",
  "root",
  "system",
  "superadmin",
  "link168",
  "verify",
  "login",
  "register",
  "dashboard",
  "settings",
  "api",
  "api-docs",
  "reports",
  "jeepwork",
  "help",
  "support",
  "legal",
  "privacy",
  "terms",
  "about",
  "about",
  "contact",
  "security",
  "dev",
  "staging",
  "test",
  "testing",
  "demo",
  "sitemap",
  "robots",
  "healthz",
  "status",
]);

const DASHBOARD_HANDLE_RESERVED_ERROR = "该公开地址不可使用，请换一个";
const DASHBOARD_HANDLE_LOCKED_ERROR = "当前已无修改次数，请联系客服";

type SaveProfileRequest = {
  username?: unknown;
  displayName?: unknown;
  bio?: unknown;
  theme?: unknown;
  language?: unknown;
  customTheme?: unknown;
  template?: unknown;
};

const PRESET_THEMES = ["Link168 草木默认", "简约白", "商务黑", "蓝色科技", "橙色活力", "浅绿清新"];

function getRequestIp(request: Request): string | undefined {
  const xff = request.headers.get("x-forwarded-for");
  if (xff) return xff.split(",")[0].trim();
  return request.headers.get("x-real-ip") || undefined;
}

async function checkUsernameAvailability(
  handle: string,
  currentUserId: string,
): Promise<{
    available: boolean;
    reserved?: boolean;
    occupiedByCurrent?: boolean;
    occupiedByOther?: boolean;
    queryFailed?: boolean;
  }> {
  const normalized = normalizeUsername(handle);
  if (RESERVED_USERNAMES.has(normalized)) return { available: false, reserved: true };

  try {
    const registryEntry = await db.usernameRegistry.findUnique({
      where: { normalizedUsername: normalized },
      select: { userId: true, status: true, reservedUntil: true },
    });

    if (registryEntry) {
      if (registryEntry.userId === currentUserId && registryEntry.status === "CURRENT") {
        return { available: true, occupiedByCurrent: true };
      }
      if (registryEntry.status === "RESERVED_90_DAYS" && registryEntry.reservedUntil && registryEntry.reservedUntil > new Date()) {
        if (registryEntry.userId === currentUserId) return { available: true, occupiedByCurrent: true };
        return { available: false };
      }
      if (registryEntry.status === "PERMANENTLY_RESERVED") return { available: false };
      if (registryEntry.userId && registryEntry.userId !== currentUserId && registryEntry.status === "CURRENT") {
        return { available: false };
      }
    }

    const existingProfile = await db.profile.findFirst({
      where: { username: { in: [handle, normalized] } },
      select: { userId: true, username: true },
    });
    if (existingProfile) {
      if (existingProfile.userId === currentUserId) return { available: true, occupiedByCurrent: true };
      return { available: false, occupiedByOther: true };
    }

    return { available: true };
  } catch {
    return { available: false, queryFailed: true };
  }
}

async function persistUsernameChange(
  userId: string,
  currentUsername: string,
  newUsername: string,
  isFirstTime: boolean,
): Promise<{ success: boolean; registryWritten: boolean; historyWritten: boolean; queryFailed?: boolean }> {
  const normalized = normalizeUsername(newUsername);
  const normalizedCurrent = normalizeUsername(currentUsername);

  try {
    if (isFirstTime) {
      try {
        // auto-generated username (user-{uuid}) 的首次用户修改需要消耗修改次数
        // placeholder 用户名（空/yourname）的首次设置不消耗次数
        const isAutoGen = isAutoGeneratedHandle(currentUsername);
        await db.$transaction([
          db.usernameRegistry.upsert({
            where: { normalizedUsername: normalized },
            create: { id: crypto.randomUUID(), normalizedUsername: normalized, displayUsername: newUsername, userId, status: "CURRENT" },
            update: { status: "CURRENT", userId, displayUsername: newUsername },
          }),
          db.usernameHistory.create({
            data: {
              id: crypto.randomUUID(),
              userId,
              username: newUsername,
              normalizedUsername: normalized,
              reservedUntil: null, // INITIAL_SET: History 仅审计，不承担实际占用
              createdAt: new Date(),
            },
          }),
          ...(isAutoGen
            ? [
                db.user.update({
                  where: { id: userId },
                  data: { usernameChanges: { decrement: 1 } },
                }),
              ]
            : []),
        ]);
        return { success: true, registryWritten: true, historyWritten: true };
      } catch {
        return { success: false, registryWritten: false, historyWritten: false, queryFailed: true };
      }
    }

    const reservedUntil = new Date(Date.now() + 90 * 24 * 60 * 60 * 1000);
    await db.$transaction([
      db.usernameRegistry.upsert({
        where: { normalizedUsername: normalizedCurrent },
        create: {
          id: crypto.randomUUID(),
          normalizedUsername: normalizedCurrent,
          displayUsername: currentUsername,
          userId,
          status: "RESERVED_90_DAYS",
          reservedUntil,
          reason: "user_changed",
        },
        update: { status: "RESERVED_90_DAYS", reservedUntil, reason: "user_changed" },
      }),
      db.usernameRegistry.upsert({
        where: { normalizedUsername: normalized },
        create: { id: crypto.randomUUID(), normalizedUsername: normalized, displayUsername: newUsername, userId, status: "CURRENT" },
        update: { status: "CURRENT", userId, displayUsername: newUsername },
      }),
      db.usernameHistory.create({
        data: {
          id: crypto.randomUUID(),
          userId,
          username: currentUsername,
          normalizedUsername: normalizedCurrent,
          replacedBy: newUsername,
          reservedUntil,
          createdAt: new Date(),
        },
      }),
      db.user.update({
        where: { id: userId },
        data: { usernameChanges: { decrement: 1 } },
      }),
    ]);
    return { success: true, registryWritten: true, historyWritten: true };
  } catch {
    return { success: false, registryWritten: false, historyWritten: false, queryFailed: true };
  }
}

export async function GET(request: Request) {
  const { user, response } = await requireDashboardUser(request);
  if (response || !user) return response;

  let restrictionQueryFailed = false;
  let restrictions: Awaited<ReturnType<typeof getActiveRestrictions>> = [];
  let loginBlocked = false;
  let loginBlockReason: string | null = null;

  if (!user.emailVerified) {
    try {
      await syncEmailVerificationRestriction(user.id);
    } catch (err) {
      if (!(err instanceof RestrictionQueryError)) throw err;
      // 表未迁移：降级，不失败
    }
  }

  try {
    restrictions = await getActiveRestrictions(user.id);
    const loginCheck = canUserLogin(restrictions);
    loginBlocked = !loginCheck.ok;
    loginBlockReason = loginCheck.reason;
  } catch (err) {
    if (err instanceof RestrictionQueryError) {
      restrictionQueryFailed = true;
    } else {
      throw err;
    }
  }

  const data = await getDashboardData(user.id);

  return NextResponse.json({
    success: !restrictionQueryFailed,
    user,
    restrictions: restrictionQueryFailed
      ? { queryFailed: true }
      : { items: restrictions, loginBlocked, loginBlockReason },
    ...data,
    meta: {
      hasUnverifiedEmail: !user.emailVerified,
      reservedUsernames: RESERVED_USERNAMES.size,
      remoteIp: process.env.NODE_ENV === "development" ? (getRequestIp(request) || "local") : undefined,
    },
  });
}

export async function PUT(request: Request) {
  const { user, response } = await requireDashboardUser(request);
  if (response || !user) return response;

  let body: SaveProfileRequest;
  try {
    body = (await request.json()) as SaveProfileRequest;
  } catch {
    return NextResponse.json({ success: false, error: "请求格式不正确。" }, { status: 400 });
  }

  const profileByUser = await db.profile.findUnique({ where: { userId: user.id } });
  const currentUsername = profileByUser?.username || "";
  const isFirstTimeSetup = !profileByUser || isPlaceholderHandle(currentUsername) || isAutoGeneratedHandle(currentUsername);

  let newUsername = currentUsername;
  const requestedHandle = typeof body.username === "string" ? body.username.trim() : "";

  if (requestedHandle) {
    const handleResult = validateHandle(requestedHandle);
    if (!handleResult.success) {
      return NextResponse.json(
        { success: false, error: handleResult.error === "已保留" ? DASHBOARD_HANDLE_RESERVED_ERROR : handleResult.error },
        { status: 400 },
      );
    }

    const availability = await checkUsernameAvailability(requestedHandle, user.id);
    if (availability.queryFailed) {
      return NextResponse.json(
        { success: false, error: "服务器繁忙，请稍后重试；您的请求未被保存。" },
        { status: 503 },
      );
    }
    if (!availability.available && !availability.occupiedByCurrent) {
      if (availability.reserved) return NextResponse.json({ success: false, error: DASHBOARD_HANDLE_RESERVED_ERROR }, { status: 409 });
      return NextResponse.json({ success: false, error: "该公开地址已被占用" }, { status: 409 });
    }

    const handleNormalized = normalizeHandle(requestedHandle);
    const currentNormalized = normalizeUsername(currentUsername);

    if (!isFirstTimeSetup && handleNormalized !== currentNormalized) {
      const userWithChanges = await db.user.findUnique({ where: { id: user.id }, select: { usernameChanges: true } });
      if (!userWithChanges || userWithChanges.usernameChanges <= 0) {
        return NextResponse.json({ success: false, error: DASHBOARD_HANDLE_LOCKED_ERROR }, { status: 403 });
      }
      const persist = await persistUsernameChange(user.id, currentUsername, requestedHandle, false);
      if (!persist.success) {
        return NextResponse.json({ success: false, error: "服务器繁忙，地址更新未保存，请稍后重试。" }, { status: 503 });
      }
      newUsername = requestedHandle;
    } else if (isFirstTimeSetup) {
      const persist = await persistUsernameChange(user.id, currentUsername || "", requestedHandle, true);
      if (!persist.success) {
        return NextResponse.json({ success: false, error: "服务器繁忙，地址更新未保存，请稍后重试。" }, { status: 503 });
      }
      newUsername = requestedHandle;
    } else {
      newUsername = requestedHandle;
    }
  }

  const themeRaw = typeof body.theme === "string" ? body.theme.trim() : "";
  const themeValue = PRESET_THEMES.includes(themeRaw) ? themeRaw : null;
  const languageRaw = typeof body.language === "string" ? body.language.trim() : "";
  const languageValue = languageRaw && ["zh", "en", "ja"].includes(languageRaw) ? languageRaw : null;
  const customThemeValue = typeof body.customTheme === "string" ? body.customTheme.trim() || null : null;
  const templateRaw = typeof body.template === "string" ? body.template.trim().toLowerCase() : "";
  const templateValue = ["business", "creator", "conversion"].includes(templateRaw) ? templateRaw : null;
  const displayName = typeof body.displayName === "string" ? body.displayName.trim() || null : null;
  const bio = typeof body.bio === "string" ? body.bio.trim() || null : null;

  const profile = await db.profile.upsert({
    where: { userId: user.id },
    create: {
      id: newId(),
      userId: user.id,
      username: newUsername || `user-${user.id.slice(0, 6)}`,
      displayName,
      bio,
      theme: themeValue || "Link168 草木默认",
      template: templateValue || "business",
      language: languageValue || "zh",
      customTheme: customThemeValue,
      isPublic: true,
    },
    update: {
      displayName,
      bio,
      ...(themeValue ? { theme: themeValue } : {}),
      ...(templateValue ? { template: templateValue } : {}),
      ...(languageValue ? { language: languageValue } : {}),
      ...(customThemeValue ? { customTheme: customThemeValue } : {}),
      isPublic: true,
      ...(newUsername && newUsername !== currentUsername ? { username: newUsername } : {}),
    },
  });

  return NextResponse.json({ success: true, profile: toProfileDto(profile) });
}
