import { NextResponse } from "next/server";
import { requireDashboardUser } from "@/lib/auth";
import { db } from "@/lib/db";

export const runtime = "nodejs";

const RESERVED_USERNAMES = new Set([
  "admin", "root", "super", "system", "link168", "link", "www",
  "api", "app", "mail", "email", "login", "logout", "register",
  "signup", "signin", "password", "reset", "verify", "dashboard",
  "profile", "user", "users", "public", "private", "settings",
  "jeepwork", "showcase", "enterprise", "enterprise-ai",
]);

const RESERVED_PREFIXES = ["user-", "admin-", "root-", "system-", "test-", "demo-"];

function isReservedUsername(username: string): boolean {
  const lower = username.toLowerCase();
  if (RESERVED_USERNAMES.has(lower)) return true;
  if (RESERVED_PREFIXES.some((p) => lower.startsWith(p))) return true;
  return false;
}

function normalizeUsername(username: string): string {
  return username.trim().toLowerCase();
}

// 判断用户名是否为系统自动生成格式
function isAutoGeneratedUsername(username: string): boolean {
  return /^user-[a-f0-9]{8}$/.test(username);
}

type UsernameSetupRequest = {
  username?: unknown;
};

function validateUsername(username: string): string | null {
  if (!username || typeof username !== "string") return "请输入用户名";
  const trimmed = username.trim();
  if (trimmed.length < 2) return "用户名至少 2 个字符";
  if (trimmed.length > 24) return "用户名最多 24 个字符";
  if (!/^[a-zA-Z0-9_\u4e00-\u9fff-]+$/.test(trimmed)) return "用户名只能包含字母、数字、下划线、汉字和短横线";
  if (/^[0-9-]/.test(trimmed)) return "用户名不能以数字或短横线开头";
  if (isReservedUsername(trimmed)) return "该用户名已被系统保留，请换一个";
  return null;
}

export async function POST(request: Request) {
  const { user, response } = await requireDashboardUser(request);
  if (response || !user) return response;

  let body: UsernameSetupRequest;
  try {
    body = (await request.json()) as UsernameSetupRequest;
  } catch {
    return NextResponse.json({ success: false, error: "请求格式不正确。" }, { status: 400 });
  }

  const username = typeof body.username === "string" ? body.username.trim() : "";

  const validationError = validateUsername(username);
  if (validationError) {
    return NextResponse.json({ success: false, error: validationError }, { status: 400 });
  }

  const normalized = normalizeUsername(username);

  // 查询当前用户的 profile
  const profile = await db.profile.findUnique({
    where: { userId: user.id },
    select: { username: true, displayName: true },
  });

  if (!profile) {
    return NextResponse.json({ success: false, error: "找不到用户资料，请先完成注册。" }, { status: 404 });
  }

  // 检查是否为自动生成的临时用户名
  const isAutoGenerated = isAutoGeneratedUsername(profile.username);

  // 如果不是自动生成的用户名，且要设置成一样的，直接成功
  if (!isAutoGenerated && profile.username.toLowerCase() === normalized) {
    return NextResponse.json({ success: true, username: profile.username, modified: false });
  }

  // 检查是否为自动生成的用户名格式，且这是第一次正式设置
  // 允许一次容错修改：如果当前是自动生成格式，无论改成什么（只要通过验证）都允许
  // 如果当前不是自动生成格式，拒绝再次修改
  if (!isAutoGenerated) {
    // 已有自定义用户名，不允许再次修改
    return NextResponse.json({
      success: false,
      error: "用户名已完成设置，不支持再次修改。如需修改请联系客服。",
      username: profile.username,
    }, { status: 409 });
  }

  // 检查 UsernameRegistry 中是否已有该用户名
  const existingRegistry = await db.usernameRegistry.findUnique({
    where: { normalizedUsername: normalized },
  });

  if (existingRegistry) {
    if (existingRegistry.status === "PERMANENTLY_RESERVED") {
      return NextResponse.json({ success: false, error: "该用户名已被永久保留，无法使用。" }, { status: 409 });
    }
    if (existingRegistry.status === "RESERVED_90_DAYS" && existingRegistry.reservedUntil && existingRegistry.reservedUntil > new Date()) {
      return NextResponse.json({ success: false, error: "该用户名处于保留期，暂时无法使用。" }, { status: 409 });
    }
    if (existingRegistry.userId && existingRegistry.userId !== user.id) {
      return NextResponse.json({ success: false, error: "该用户名已被其他用户使用，请换一个。" }, { status: 409 });
    }
  }

  // 检查 Profile 表中是否已有该用户名（直接查询 Profile 而非通过 registry）
  const existingProfileUsername = await db.profile.findFirst({
    where: {
      username: { equals: normalized, mode: "insensitive" as const },
      userId: { not: user.id },
    },
  });

  if (existingProfileUsername) {
    return NextResponse.json({ success: false, error: "该用户名已被其他用户使用，请换一个。" }, { status: 409 });
  }

  // 保留旧用户名 90 天（如果是自动生成格式）
  const oldNormalized = profile.username ? normalizeUsername(profile.username) : null;

  try {
    await db.$transaction([
      // 创建新的 UsernameRegistry 条目
      db.usernameRegistry.create({
        data: {
          id: crypto.randomUUID(),
          normalizedUsername: normalized,
          displayUsername: username.trim(),
          userId: user.id,
          status: "CURRENT",
          reason: "user_setup",
        },
      }),
      // 更新 Profile 的用户名
      db.profile.update({
        where: { userId: user.id },
        data: { username: normalized },
      }),
      // 如果旧用户名是自动生成格式，保留 90 天
      ...(oldNormalized && oldNormalized !== normalized
        ? [
            db.usernameRegistry.updateMany({
              where: {
                normalizedUsername: oldNormalized,
                status: "CURRENT",
                userId: user.id,
              },
              data: {
                status: "RESERVED_90_DAYS",
                reservedUntil: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
                reason: "user_changed",
                userId: null,
              },
            }),
          ]
        : []),
    ]);
  } catch {
    return NextResponse.json({ success: false, error: "用户名设置失败，请稍后重试。" }, { status: 500 });
  }

  return NextResponse.json({
    success: true,
    username: normalized,
    modified: true,
    message: "用户名设置成功！",
  });
}
