"use client";

import { useState } from "react";

interface Props {
  currentUsername: string;
  isAutoGenerated: boolean;
  onUsernameSet?: (username: string) => void;
}

export default function UsernameSetupPrompt({ currentUsername, isAutoGenerated, onUsernameSet }: Props) {
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [done, setDone] = useState(false);

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    setMessage("");
    setError("");

    if (!input.trim()) {
      setError("请输入用户名");
      return;
    }

    setLoading(true);
    try {
      const response = await fetch("/api/auth/username", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username: input.trim() }),
      });
      const result = (await response.json()) as { success?: boolean; error?: string; username?: string; modified?: boolean; message?: string };

      setLoading(false);

      if (!response.ok || !result.success) {
        setError(result.error || "设置失败，请稍后重试。");
        return;
      }

      setDone(true);
      setMessage(result.message || "用户名设置成功！");
      onUsernameSet?.(result.username || input.trim());
    } catch {
      setLoading(false);
      setError("网络错误，请稍后重试。");
    }
  }

  if (done) {
    return (
      <div className="rounded-2xl border border-[#DDE8CD] bg-[#DDE8CD]/30 p-5 text-center sm:rounded-[24px] sm:p-6">
        <p className="text-sm font-black text-[#3F5F31]">✅ {message}</p>
        <p className="mt-2 break-all text-xs text-[#7A6D5E]">
          你的公开主页地址：/{input.trim()}
        </p>
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-[#F6E7C8] bg-[#F6E7C8]/40 p-4 sm:rounded-[24px] sm:p-5">
      <p className="text-sm font-black text-[#8C612E]">⚠️ 请先设置你的公开地址</p>
      <p className="mt-1 text-xs text-[#7A6D5E]">
        设置后你的公开主页将显示为 link168.me/
        <span className="font-bold">{input.trim() || "你的用户名"}</span>
        。设置成功后，如需修改可再改一次，之后将锁定。
      </p>

      <form onSubmit={handleSubmit} className="mt-4 grid gap-3">
        <div className="flex items-center gap-2 rounded-2xl border border-[#E8DCCB] bg-white px-3 py-2 sm:px-4">
          <span className="shrink-0 text-xs text-[#7A6D5E] sm:text-sm">link168.me/</span>
          <input
            required
            value={input}
            onChange={(e) => setInput(e.target.value.toLowerCase().replace(/[^a-z0-9_-]/g, ""))}
            placeholder="你的用户名"
            maxLength={24}
            className="min-w-0 flex-1 bg-transparent text-sm font-bold text-[#2B241E] outline-none placeholder:text-[#A69A8A]"
          />
        </div>

        {error && (
          <p className="rounded-xl bg-[#FFE6E2] px-4 py-2 text-xs font-bold text-[#B42318]">
            {error}
          </p>
        )}
        {message && (
          <p className="rounded-xl bg-[#DDE8CD]/60 px-4 py-2 text-xs font-bold text-[#3F5F31]">
            {message}
          </p>
        )}

        <button
          type="submit"
          disabled={loading}
          className="link168-button-press flex h-11 w-full items-center justify-center gap-2 rounded-full bg-[#6F8F4E] px-5 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-60"
        >
          {loading ? "设置中..." : "确认并设置公开地址"}
        </button>
      </form>

      <p className="mt-3 text-center text-xs text-[#A69A8A]">
        用户名设置后可更改一次，之后将永久锁定，请谨慎选择。
      </p>
    </div>
  );
}
